---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: keip-integrationroute-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: keip.codice.org/v1alpha2
    resource: integrationroutes
    revisionHistory:
      fieldPaths:
        - spec.routeConfigMap
  childResources:
    - apiVersion: apps/v1
      resource: deployments
      updateStrategy:
        method: RollingRecreate
        statusChecks:
          conditions:
            - type: Ready
              status: "True"
    - apiVersion: v1
      resource: services
      updateStrategy:
        method: RollingRecreate
  hooks:
    sync:
      webhook:
        # TODO: Migrate to HTTPS. Sync requests contain CR specs with secret references.
        url: http://integrationroute-webhook.keip/webhook/sync
        timeout: 10s
